name: CI
on:
    push:
        branches-ignore: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        name: Run NPM
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - name: Use Node.js - 14.15
              uses: actions/setup-node@v2
              with:
                node-version: 14.15
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm build:ci
            - name: Test
              run: npm test:ci
            - name: Lint Code Base
              uses: github/super-linter@v3
              env:
                VALIDATE_ALL_CODEBASE: false
                DEFAULT_BRANCH: main
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}